apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cd-webca-io-certificate
  namespace: webca
spec:
  dnsNames:
    - cd.webca.io
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: cd-webca-io-certificate
