kind: Service
apiVersion: v1
metadata:
  name: argocd
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
  ports:
    - name: https
      protocol: "TCP"
      port: 443
