name: api-server-pipeline
on: 
  push:
    paths:
      - api-server/**

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Checkout code
      uses: actions/checkout@v2
    - name: print base cwd
      run: ls
    - name: print api-server cwd
      run: ls
      working-directory: ./api-server
    - name: Get dependencies
      run: go mod download
      working-directory: ./api-server
    - name: Test
      run: go test ./...
      working-directory: ./api-server