name: deployment-pipeline
on:
  push:
    paths:
      - end-to-end-tests/**
      - .github/workflows/deployment-pipeline.yml

jobs:
  api-tests:
    name: api-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: pip install -r requirements.txt
        working-directory: ./end-to-end-tests
      - name: Setup and run API tests
        run: |
          docker login https://docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          sh setup-environment.sh
          resttest run --port 28080
        working-directory: ./end-to-end-tests

  end-to-end-tests:
    name: end-to-end-tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.0
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: npm install
        working-directory: ./end-to-end-tests
      - name: Setup and run E2E tests
        run: |
          docker login https://docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          npm run setup
          npm test
        working-directory: ./end-to-end-tests

  update-kubernetes-manifests:
    name: update-kubernetes-manifests
    needs:
      - api-tests
      - end-to-end-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Update manifests
        run: sh scripts/update-images.sh
      - name: Commit k8s updates
        run: |
          git config --global user.name 'CI/CD bot'
          git config --global user.email 'cicd.bot@webca.io'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          commit_date=$(date +'%Y-%m-%d %H:%M:%S')
          git commit -am "Updated k8s manifests. date = $commit_date"
          git diff HEAD^ k8s
          git push
